# This is a basic workflow to help you get started with Actions

name: Python test

# Controls when the workflow will run
on: [push]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run tests
        run: "python -m unittest test_calculator"

    
